version: '3'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  add-segmento-a:
    build: './agregar_segmento'
    depends_on:
      - redis
    volumes:
      - ./agregar_segmento:/code
    command: python alimentar_palabra.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis

  add-segmento-b:
    build: './agregar_segmento'
    depends_on:
      - redis
    volumes:
      - ./agregar_segmento:/code
    command: python alimentar_palabra.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis      

  add-segmento-c:
    build: './agregar_segmento'
    depends_on:
      - redis
    volumes:
      - ./agregar_segmento:/code
    command: python alimentar_palabra.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis    
      
  comb-segmento:
    build: './combinar_segmentos'
    depends_on:
      - redis
    volumes:
      - ./combinar_segmentos:/code
    command: python combinar_palabras.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis

  print-comb:
    build: './imprimir_codigos'
    depends_on:
      - redis
    volumes:
      - ./imprimir_codigos:/code
    command: python leer_codigos.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis